spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://your-dev-db-host:5432/your-dev-db
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-dev-google-client-id
            client-secret: your-dev-google-client-secret
            scope:
              - profile
              - email
          kakao:
            client-id: your-dev-kakao-client-id
            client-secret: your-dev-kakao-client-secret
            redirect-uri: https://your-dev-server/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email